### ISSUE TITLE
Too high idle temperature of my RX580 2048sp

### ISSUE THREAD

**Issue by S1lenix** [danfq/Ryzentosh-Sonoma#1]
After flashing your VBIOS my Rx580 2048sp hits high idle temperatures (~68-75) and high idle consumption, before I tested it only in windows with my stock VBIOS, temperatures was about (~34-45) and idle consumption was 30-60w. What can you say about this? Is this a macOS or VBIOS issue? Also, after switching to this VBIOS, I began to notice rare artifacts.

**Comment by danfq** [comment]
When idle, my GPU hits around 50º to 60º, with a max of 60W consumption.
I'm running macOS Sonoma (14.5).

As for the artifacts; I have no artifacts.
That appears to be related to your GPU - which may have been used for crypto-mining in the past.
This is a quite common scenario when buying this card, from China - and it "burns" your chips, producing artifacts.

As for Windows usage; I don't use it on Windows - I have a Sapphire RX 7600XT for gaming.
Therefore, I am unable to provide you with "sample" values for the "RX580" on Windows.
